# Setup
title: [AGAT]
description: [From Behind the Camera to on the Screen]
# theme: jekyll-theme-awesome
# theme: jekyll-theme-primer
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown:           kramdown
kramdown:
    math_engine:    katex